### ISSUE TITLE
Getting 404 after 

### ISSUE THREAD

**Issue by Thaurin** [diego-treitos/nginx_waf#1]
Hi. I found your blog post and this WAF for nginx seems exactly what I want for the reasons you mentioned in the post (having to train naxsi, recompile nginx, etc.). However, after setting up `nginx_waf`, I'm getting 404 on my sites.

I'm pretty new to nginx, so this is probably my fault. But can you give me any idea of what I did wrong? I set up a location within one of my sites' server blocks, for example:

```
location @waf-blocked {
    deny all;
}
```

but I am not sure if that what the README meant or what I should put into the location block. But regardless of the things that I tried, if I put the LUA files in my `nginx.conf` file, I'll get 404 on *all* my sites.

Great stuff, though, if I could get it to work. I'd rather stick with `apt` packages for nginx instead of having to manage updates manually when compiling a WAF from source!

**Comment by diego-treitos** [comment]
Hi @Thaurin, to clarify a bit how `nginx_waf` works, here is what happens when a request arrives:

1. A request is received and it is passed to `nginx_waf`
2. `nginx_waf` checks if the **domain** for the request is **whitelisted**, *if it is continue normally*
3. `nginx_waf` checks if the request matches any of the rules. *If it doesn't or if the rule is whitelisted, continue normally*
4. `nginx_waf` sends the request to the location configured in the `nw_location_denied` parameter of the `/etc/nginx/waf/config.lua` file. In your case `'@waf-blocked'`.
5. Nginx will do anything you specify in the `@waf-blocked` location.

In your case, nginx should be returning `403` because of `deny all`.

I would need more information to know what might be wrong in your site:

* Are you getting 404 in all your pages or only the waf triggered ones?
* What is your `nginx_waf` config?
* What LUA lines are you adding to your `nginx.conf`?
* Is there anything showing in the nginx `error.log`?

**Comment by Thaurin** [comment]
I'm not sure what I did differently now, but I uncommented the LUA files in `nginx.conf` again and re-added the `@waf-blocked` locations to two server blocks, and the sites still seem to be working, no 404's. I must've been very tired yesterday.

But is there some way that I can check that it's actually running as it should? No log file is created at `/var/log/nginx/waf.log`. When I intentionally misconfigure `nginx.conf` I do get errors in `error.log` and a 404 when I load the site, so maybe I forgot to set file permissions before and got a permission denied for the LUA files.

My `nginx_waf` config is unchanged from what's in your repo and all the directory names should be correct (Ubuntu 18.04).

`nginx.conf`:
```
lua_package_path   "/etc/nginx/waf/?.lua;;";
init_by_lua_file   "/etc/nginx/waf/init.lua";
access_by_lua_file "/etc/nginx/waf/waf.lua";
```

I'd like to see some sign of life from `nginx_waf` so I can be sure that it's doing something. :)

**Comment by Thaurin** [comment]
I've put:

```
ngx.log( ngx.ERR, 'WAF: Reporting for duty! '..nw_log_file )
```

in `init.lua` and the message does appear in `error.log`, so at least I'm sure that the LUA files are loaded (on nginx restart).

**Comment by diego-treitos** [comment]
You can test making a request to `https://yourdomain/<script>alert(1)</script>`. That should trigger the WAF and log something in the log file.

**Comment by diego-treitos** [comment]
NOTE: Due to permissions, you might want to change the log file to `/var/log/nginx/waf/waf.log` and then execute as root:

```
mkdir /var/log/nginx/waf
chown www-data:ww-data /var/log/nginx/waf
chmod 640 /var/log/nginx/waf
```

And then restart nginx

**Comment by Thaurin** [comment]
Success! There was *indeed* a permissions issue, but I had to `chmod 750 /var/log/nginx/waf` the log directory. Your test request was also very useful for testing that the WAF was working. It might be helpful to clarify these things in the `README.md`. I wrongly assumed that the log file would be written as root.

Will you keep updating and extending the ruleset? Will it be anywhere near the core ruleset of modsecurity, for example?

Thanks for the help!

**Comment by diego-treitos** [comment]
I am glad it is working! I will definitely add that to the README.

I will also keep working on the ruleset and the code ;)
